// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqpuzknmednnsybsyoaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxcHV6a25tZWRubnN5YnN5b2F6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMTM2NDEsImV4cCI6MjA2MDc4OTY0MX0.8c9lsXjbT1o-LnNek94zJndfDSXH5b_G71lZ03Ay5Z8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);